name: test-coverage

on:
  push: { branches: [ master ] }
  pull_request: { branches: [ master ] }

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::covr
            any::DT
            any::htmltools
          needs: coverage

      - name: Compute coverage
        shell: Rscript {0}
        run: |
          cov <- covr::package_coverage(quiet = FALSE, clean = FALSE)
          print(cov)
          covr::to_cobertura(cov, file = "cobertura.xml")
          covr::report(cov, file = "coverage.html")

      - name: Upload HTML coverage (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: coverage.html

      - name: Verify cobertura exists
        run: ls -l cobertura.xml

      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        continue-on-error: true
        with:
          files: cobertura.xml
          disable_search: true
          verbose: true

